#!/usr/bin/bash

# backup old grub config if needed

# Make sure the displayed text is Lingmo OS
sed -i 's/^#\?GRUB_DISTRIBUTOR=.*/GRUB_DISTRIBUTOR="Lingmo OS"/' /etc/default/grub

sed -i 's/^#\?GRUB_THEME=.*/GRUB_THEME="\/boot\/grub\/themes\/lingmo\/theme.txt"/' /etc/default/grub

# Update GRUB config
/usr/sbin/update-grub