#!/usr/bin/bash

# backup old grub config if needed

if [ -f "/etc/default/grub" ]; then
    mv /etc/default/grub /etc/default/grub.backup
fi

if [ -f "/usr/share/grub/default/grub" ]; then
    mv /usr/share/grub/default/grub /usr/share/grub/default/grub.backup
fi

cp /usr/share/grub/default/grub.lingmo /usr/share/grub/default/grub
cp /usr/share/grub/default/grub.lingmo /etc/default/grub
